name: AMAI Build CI
on:
  push:
    branches: [ "master" ]
    paths:
      - '上传/上传占位符.txt'
      - '.github/workflows/amaibuild.yml'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
        working-directory: ./S
    - run: perl -V    
    - run: ./MAKEAMAIONLINE.BAT
    - uses: actions/upload-artifact@v3
      with:
        path: ./上传
    - uses: actions/download-artifact@v4
      with:
        path: ./
