name: AMAI 编译工作流（基于3.3.2，仅支持重制版）
on:
  push:
    branches: [ "master" ]
    paths:
      - 'MAKEAMAIONLINE.BAT'
      - '.github/workflows/amaibuild.yml'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
        working-directory: ./
    - run: perl -V    
    - run: ./MAKEAMAIONLINE.BAT
    - uses: actions/upload-artifact@v3
      with:
        path: ./
    - uses: actions/download-artifact@v4
      with:
        path: ./
