name: AMAI 编译工作流（基于3.3.2，仅支持重制版）
on:
  push:
    branches: [ "master" ]
    paths:
      - 'MAKEAMAIONLINE.BAT'
      - '.github/workflows/amaibuild.yml'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - name: 提交源码
      uses: actions/checkout@v4
    - name: 安装编译环境
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
        working-directory: ./
    - name: 运行编译工具
      run: perl -V
    - name: 编译
      run: ./MAKEAMAIONLINE.BAT
    - name: 压缩脚本
      uses: darshitsri/zip-release@v3
      with:
        filename: amai.zip
        path:  D:/a/AMAI/AMAI/AMAI
        directory: D:/a/AMAI/AMAI/AMAI
    - name: 上传压缩包
      uses: actions/upload-artifact@v4
      with:
        path: ./AMAI/amai.zip
    - name: 下载压缩包
      uses: actions/download-artifact@v4
