name: AMAI Build CI
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'LICENSE'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
        working-directory: ./S
    - run: perl -V    
    - run: ./MakeTFT.bat
    - uses: actions/upload-artifact@v3
      with:
        path: ./S
    - uses: actions/download-artifact@v4
      with:
        path: ./下载
