name: AMAI Build CI
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'LICENSE'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
    - cache: ./back   # 指定要缓存的本地路径
    - cache: ./download   # 指定要缓存的本地路径
    - run: perl -V    
    - run: ./MakeAMAIonline.bat
